USE [OneSource]
GO

-- NEEDS TO PUT THIS FIELD RIGHT AFTER THE FIRSTNAME COLUMN, BECAUSE OF THE BULKCOPY
ALTER TABLE CS_Employee_Load ADD Nickname VARCHAR(30) NULL
GO

ALTER TABLE CS_Employee ADD Nickname VARCHAR(30) NULL
GO